<a href="https://colab.research.google.com/github/Tanya-23-lessgo/house-rent-prediction/blob/main/Mark_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# Install dependencies as needed:
# pip install kagglehub[pandas-datasets]
import kagglehub
from kagglehub import KaggleDatasetAdapter

path=kagglehub.dataset_download("whenamancodes/student-performance")
print("Path to dataset files:", path)

Using Colab cache for faster access to the 'student-performance' dataset.
Path to dataset files: /kaggle/input/student-performance

In [15]:
import os
path="/kaggle/input/student-performance"
os.listdir(path)

['Maths.csv', 'Portuguese.csv']

In [17]:
import pandas as pd
df=pd.read_excel(f"{path}/Maths.csv")

In [18]:
df.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 397 entries, 0 to 396
Data columns (total 33 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   school      397 non-null    object
 1   sex         397 non-null    object
 2   age         397 non-null    int64
 3   address     397 non-null    object
 4   famsize     397 non-null    object
 5   Pstatus     397 non-null    object
 6   Medu        397 non-null    int64
 7   Fedu        397 non-null    int64
 8   Mjob        397 non-null    object
 9   Fjob        397 non-null    object
 10  reason      397 non-null    object
 11  guardian    397 non-null    object
 12  traveltime  397 non-null    int64
 13  studytime   397 non-null    int64
 14  failures    397 non-null    int64
 15  schoolsup   397 non-null    object
 16  famsup      397 non-null    object
 17  paid        397 non-null    object
 18  activities  397 non-null    object
 19  nursery     397 non-null    object
 20  higher      397 non-null    object
 21  internet    397 non-null    object
 22  romantic    397 non-null    object
 23  famrel      397 non-null    int64
 24  freetime    397 non-null    int64
 25  goout       397 non-null    int64
 26  Dalc        397 non-null    int64
 27  Walc        397 non-null    int64
 28  health      397 non-null    int64
 29  absences    397 non-null    int64
 30  G1          397 non-null    int64
 31  G2          397 non-null    int64
 32  G3          397 non-null    int64
dtypes: int64(16), object(17)
memory usage: 102.5+ KB

In [34]:
to_drop = [
    "school","famsize","Pstatus","Mjob","Fjob","reason","guardian",
    "traveltime","famsup","paid","activities","nursery","higher",
    "internet","romantic",
    "sex","address"
]

df2 = df.drop(columns=to_drop)

In [33]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [37]:
for col in df2.columns:
  if df2[col].dtype=="object":
    df2[col]=le.fit_transform(df2[col])

In [19]:
df.isnull().sum()

school        0
sex           0
age           0
address       0
famsize       0
Pstatus       0
Medu          0
Fedu          0
Mjob          0
Fjob          0
reason        0
guardian      0
traveltime    0
studytime     0
failures      0
schoolsup     0
famsup        0
paid          0
activities    0
nursery       0
higher        0
internet      0
romantic      0
famrel        0
freetime      0
goout         0
Dalc          0
Walc          0
health        0
absences      0
G1            0
G2            0
G3            0
dtype: int64

In [39]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error,r2_score

In [43]:
y=df2["G3"]
x=df2.drop("G3",axis=1)

In [44]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [45]:
model=LinearRegression()
model.fit(x_train,y_train)

LinearRegression()

In [47]:
y_pred=model.predict(x_test)

In [48]:
print("Mean absolute error:",mean_absolute_error(y_test,y_pred))

Mean absolute error: 1.0617860416734999

In [49]:
print("R2 Error:",r2_score(y_test,y_pred))

R2 Error: 0.8681400681929635

In [56]:
sample=x_test.iloc[0]
predicted_mark=model.predict([sample])
print(f"\nPredicted mark:{predicted_mark}")
print("Actual mark:", y_test.iloc[0])

Predicted mark:[9.1766545]
Actual mark: 9

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(